export type Stamp = {
  name: string
  slug: string
  url: string
  category: string
  denom: string
  year: string
  rotation: string
  wide: boolean
  comingSoon: boolean
  image: string
  description: string
}

export type Chapter = {
  numeral: string
  title: string
  intro: string
  stamps: Stamp[]
}

export const chapters: Chapter[] = [
  {
    numeral: 'I',
    title: 'Sustainability & Energy',
    intro: 'Clean energy made legible — the work closest to the consulting.',
    stamps: [
      {
        name: 'Solar Currents',
        slug: 'solar-currents',
        url: 'https://www.solarcurrents.co',
        category: 'Solar · Clean Energy',
        denom: '32¢',
        year: '’22',
        rotation: '-2.4deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/solar-currents.jpg',
        description: 'Solar energy information, news, and guidance for homeowners and businesses navigating the transition to clean energy.',
      },
      {
        name: 'Battery Trail',
        slug: 'battery-trail',
        url: 'https://www.batterytrail.com',
        category: 'Energy · Storage',
        denom: '29¢',
        year: '’23',
        rotation: '1.8deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/battery-trail.jpg',
        description: 'Tracking the battery storage and energy transition landscape, covering products, news, and resources for the emerging home energy ecosystem.',
      },
    ],
  },
  {
    numeral: 'II',
    title: 'Outdoor Resource Hubs',
    intro: 'A soaking network across the American West, plus a little recreation.',
    stamps: [
      {
        name: 'Soak Colorado',
        slug: 'soak-colorado',
        url: 'https://www.soakcolorado.com',
        category: 'Directory · Hot Springs',
        denom: '44¢',
        year: '’19',
        rotation: '2.6deg',
        wide: true,
        comingSoon: false,
        image: '/stamps/soak-colorado.jpg',
        description: 'Hot springs, wild soaks, and thermal pools across Colorado. The most comprehensive guide to soaking in the Rockies.',
      },
      {
        name: 'Soak the Rockies',
        slug: 'soak-the-rockies',
        url: 'https://www.soaktherockies.com',
        category: 'Directory · Hot Springs',
        denom: '37¢',
        year: '’20',
        rotation: '-2.9deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/soak-the-rockies.jpg',
        description: 'A regional overview of hot springs and soaking destinations across the Rocky Mountain corridor.',
      },
      {
        name: 'Washington Hot Springs',
        slug: 'washington-hot-springs',
        url: 'https://www.washingtonhotsprings.com',
        category: 'Directory · Hot Springs',
        denom: '55¢',
        year: '’20',
        rotation: '1.1deg',
        wide: true,
        comingSoon: false,
        image: '/stamps/washington-hot-springs.jpg',
        description: 'The definitive guide to hot springs in Washington State, from roadside soaks to backcountry pools.',
      },
      {
        name: 'Desert Soak',
        slug: 'desert-soak',
        url: 'https://www.desertsoak.com',
        category: 'Directory · Hot Springs',
        denom: '34¢',
        year: '’21',
        rotation: '-1.7deg',
        wide: true,
        comingSoon: false,
        image: '/stamps/desert-soak.jpg',
        description: 'Hot springs and soaking destinations across the American Southwest desert regions.',
      },
      {
        name: 'Shasta Hot Springs',
        slug: 'shasta-hot-springs',
        url: 'https://www.shastahotsprings.com',
        category: 'Directory · Hot Springs',
        denom: '22¢',
        year: '’21',
        rotation: '2.1deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/shasta-hot-springs.jpg',
        description: 'A focused guide to hot springs and soaking near Mount Shasta and Northern California.',
      },
      {
        name: 'Soak Trail',
        slug: 'soak-trail',
        url: 'https://www.soaktrail.com',
        category: 'Directory · Outdoors',
        denom: '46¢',
        year: '’22',
        rotation: '-2.2deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/soak-trail.jpg',
        description: 'A trail-based approach to soaking, linking hot springs to hiking routes and outdoor itineraries across the West.',
      },
      {
        name: 'Find Frolf',
        slug: 'find-frolf',
        url: 'https://www.findfrolf.com',
        category: 'Directory · Recreation',
        denom: '18¢',
        year: '’26',
        rotation: '1.5deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/find-frolf.jpg',
        description: 'A disc golf course finder and community directory, because not everything has to be serious.',
      },
    ],
  },
  {
    numeral: 'III',
    title: 'Wellness',
    intro: 'Moving through the world with intention and care.',
    stamps: [
      {
        name: 'Sound Dip',
        slug: 'sound-dip',
        url: 'https://www.sounddip.com',
        category: 'Directory · Outdoors',
        denom: '41¢',
        year: '’23',
        rotation: '-1.0deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/sound-dip.jpg',
        description: 'Cold water and wild swimming in the Puget Sound region, where outdoor dipping culture meets the Pacific Northwest.',
      },
      {
        name: 'ContrastMap',
        slug: 'contrast-map',
        url: 'https://www.contrastmap.com',
        category: 'Directory · Wellness',
        denom: '38¢',
        year: '’26',
        rotation: '2.2deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/contrast-map.jpg',
        description: 'The directory for contrast therapy — cold plunge and infrared sauna studios near you, plus the tubs and saunas for building the ritual at home.',
      },
      {
        name: 'Nourished Journeys',
        slug: 'nourished-journeys',
        url: 'https://www.nourishedjourneys.com',
        category: 'Wellness · Travel',
        denom: '68¢',
        year: '’24',
        rotation: '2.8deg',
        wide: true,
        comingSoon: false,
        image: '/stamps/nourished-journeys.jpg',
        description: 'Travel and wellness content for the intentional traveler, covering where to go, what to eat, and how to move through the world with care.',
      },
    ],
  },
  {
    numeral: 'IV',
    title: 'Local Gardeners Guide',
    intro: 'Growing, foraging, and telling the truth about the land.',
    stamps: [
      {
        name: 'Keystone Nurseries',
        slug: 'keystone-nurseries',
        url: 'https://www.keystonenurseries.com',
        category: 'Land · Sustainability',
        denom: '25¢',
        year: '’23',
        rotation: '-2.6deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/keystone-nurseries.jpg',
        description: 'A resource for native plants, keystone species, and ecological gardening, growing landscapes that support biodiversity.',
      },
      {
        name: 'HarvestMap',
        slug: 'harvest-map',
        url: 'https://harvestmap.co',
        category: 'Sustainability · Food',
        denom: '30¢',
        year: '’26',
        rotation: '1.3deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/harvest-map.jpg',
        description: 'A directory mapping local farms, u-picks, and harvest experiences — find what is ripe near you, and the land that grew it.',
      },
      {
        name: 'Gaia Verity',
        slug: 'gaia-verity',
        url: 'https://www.gaiaverity.com',
        category: 'Sustainability',
        denom: '50¢',
        year: '’24',
        rotation: '-1.9deg',
        wide: true,
        comingSoon: false,
        image: '/stamps/gaia-verity.jpg',
        description: 'A platform exploring environmental truth and sustainability accountability, where data and values intersect.',
      },
    ],
  },
  {
    numeral: 'V',
    title: 'Tools & Platforms',
    intro: 'Small machines that solve specific problems for specific people.',
    stamps: [
      {
        name: 'My MCP Shelf',
        slug: 'my-mcp-shelf',
        url: 'https://www.mymcpshelf.com',
        category: 'Tool · AI',
        denom: '99¢',
        year: '’25',
        rotation: '-1.4deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/my-mcp-shelf.jpg',
        description: 'A resource for Model Context Protocol tools and integrations, built for developers and AI practitioners exploring the MCP ecosystem.',
      },
      {
        name: 'LinkCanary',
        slug: 'link-canary',
        url: 'https://linkcanary.io',
        category: 'Tool · Publishing',
        denom: '20¢',
        year: '’26',
        rotation: '2.3deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/link-canary.jpg',
        description: 'A link monitoring and management tool, built for publishers and site owners who need to know when their links break or redirect.',
      },
      {
        name: 'Gannet',
        slug: 'gannet',
        url: 'https://github.com/Phinneas/gannet',
        category: 'Tool · AI',
        denom: '27¢',
        year: '’26',
        rotation: '-2.5deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/gannet.jpg',
        description: 'An open-source LLM visibility tracker that runs your prompts against OpenAI, Anthropic, Gemini, and Perplexity, then tells you whether you got cited — or who got cited instead.',
      },
      {
        name: 'Barnacle',
        slug: 'barnacle',
        url: 'https://github.com/Phinneas/barnacle',
        category: 'Tool · Developer',
        denom: '12¢',
        year: '’26',
        rotation: '1.9deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/barnacle.jpg',
        description: 'An audit tool for AI agent configuration. Skills, commands, and MCP servers accumulate on a project like growth on a hull — this scrapes them back off.',
      },
      {
        name: 'Portage',
        slug: 'portage',
        url: 'https://portage.tools',
        category: 'Tool · Migration',
        denom: '39¢',
        year: '’26',
        rotation: '-1.1deg',
        wide: true,
        comingSoon: false,
        image: '/stamps/portage.jpg',
        description: 'A migration tool for carrying a site from one platform to another intact, preserving content, structure, and links through the move.',
      },
    ],
  },
  {
    numeral: 'VI',
    title: 'Directories',
    intro: 'Indexes for things that are otherwise hard to find.',
    stamps: [
      {
        name: 'The Juice Index',
        slug: 'the-juice-index',
        url: 'https://www.thejuiceindex.com',
        category: 'Directory · Wellness',
        denom: '13¢',
        year: '’24',
        rotation: '-1.2deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/the-juice-index.jpg',
        description: 'A guide to juice bars, cold press, and functional beverages, mapping the wellness beverage landscape for conscious consumers.',
      },
      {
        name: 'Bin Locators',
        slug: 'bin-locators',
        url: '',
        category: 'Directory · Sustainability',
        denom: '—',
        year: 'PENDING',
        rotation: '2.0deg',
        wide: false,
        comingSoon: true,
        image: '/stamps/bin-locators.jpg',
        description: 'A directory for finding recycling, composting, and waste diversion resources by location, making responsible disposal easier.',
      },
    ],
  },
  {
    numeral: 'VII',
    title: 'Newsletters',
    intro: 'Words that arrive on a schedule.',
    stamps: [
      {
        name: 'Brain Scriblr',
        slug: 'brain-scriblr',
        url: 'https://www.mymcpshelf.com/blog?track=ai-field-notes',
        category: 'Newsletter',
        denom: '15¢',
        year: '’25',
        rotation: '-2.7deg',
        wide: true,
        comingSoon: false,
        image: '/stamps/brain-scriblr.jpg',
        description: 'A newsletter at the edges of ideas, covering technology, culture, and the things worth thinking about.',
      },
      {
        name: 'SignalField',
        slug: 'signal-field',
        url: 'https://www.mymcpshelf.com/blog?track=signal-field',
        category: 'Newsletter',
        denom: '24¢',
        year: '’26',
        rotation: '2.4deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/signal-field.jpg',
        description: 'Field notes on the AI tooling landscape, tracking what is actually signal in a space that generates a great deal of noise.',
      },
      {
        name: 'SolarPunk Currents',
        slug: 'solarpunk-currents',
        url: 'https://phinneas.substack.com/',
        category: 'Newsletter',
        denom: '45¢',
        year: '’25',
        rotation: '-1.8deg',
        wide: true,
        comingSoon: false,
        image: '/stamps/solarpunk-currents.jpg',
        description: 'A newsletter on solarpunk futures, clean energy, and the stubbornly optimistic edge of the climate transition.',
      },
    ],
  },
  {
    numeral: 'VIII',
    title: 'Studio & Courses',
    intro: 'Where the practice meets other people — building for them, and teaching them.',
    stamps: [
      {
        name: 'Salish Sea Creatives',
        slug: 'salish-sea-creatives',
        url: 'https://salishseacreative.com',
        category: 'Studio · Web Design',
        denom: '75¢',
        year: '’26',
        rotation: '-2.1deg',
        wide: true,
        comingSoon: false,
        image: '/stamps/salish-sea-creatives.jpg',
        description: 'My design studio. Production-ready Astro, Ghost, and Framer website templates for developers, authors, and creatives who mean it.',
      },
      {
        name: 'Admit Writers',
        slug: 'admit-writers',
        url: 'https://www.admitwriters.com',
        category: 'Course · Education',
        denom: '63¢',
        year: '’24',
        rotation: '1.6deg',
        wide: false,
        comingSoon: false,
        image: '/stamps/admit-writers.jpg',
        description: 'A platform connecting college applicants with essay coaches and admissions writers, because the right words open doors.',
      },
    ],
  },
]

// ponytail: derived so the hero counts can't drift from the data again.
export const stampCounts = (() => {
  const all = chapters.flatMap(c => c.stamps)
  const forthcoming = all.filter(s => s.comingSoon).length

  return { total: all.length, open: all.length - forthcoming, forthcoming }
})()
